FROM node:20.10-slim

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

RUN npm -g install pnpm

ARG SERVICE_DIR
COPY service-shared /service-shared
COPY ./${SERVICE_DIR} /app
COPY service-jobs/protos/service-jobs.proto /app/protos/service-jobs.proto

WORKDIR /service-shared
RUN pnpm install --fix-lockfile --prefer-offline

WORKDIR /app
RUN npm -g install pnpm
RUN pnpm install --fix-lockfile --prefer-offline
RUN bash proto-gen.sh

CMD ["pnpm", "start"]
